package com.example.spoti5.firebase.event

object EventName {
    const val splash_open = "splash_open"
    const val language_fo_open = "language_fo_open"
    const val language_fo_save_click = "language_fo_save_click"
    const val language_fo_choose = "language_fo_choose"
    const val onboarding_1_view = "onboarding1_view"
    const val onboarding_next_click = "onboarding_next_click"
    const val onboard_open = "onboard_open"
    const val permission_open = "permission_open"
    const val permission_allow_click = "permission_allow_click"
    const val permission_continue_click = "permission_continue_click"

    const val home_view = "home_view"
    const val home_open = "home_open"
    const val home_all_click = "home_all_click"
    const val home_PDF_click = "home_PDF_click"
    const val home_word_click = "home_word_click"
    const val home_exel_click  = "home_exel_click"
    const val home_PPT_click = "home_PPT_click"
    const val home_favorite_click = "home_favorite_click"
    const val home_search_click = "home_search_click"
    const val rename_click = "rename_click"
    const val share_file_click = "share_file_click"
    const val delete_file_click = "delete_file_click"
    const val more_info_click = "more_info_click"
    const val file_click = "file_click"
    const val read_file_view = "read_file_view"
    const val PDF_hightlight_click = "PDF_hightlight_click"
    const val PDF_underlight_click = "PDF_underlight_click"
    const val PDF_strike_thought_click = "PDF_strike_thought_click"
    const val PDF_draw_click = "PDF_draw_click"
    const val PDF_earser_click = "PDF_earser_click"
    const val PDF_copy_click = "PDF_copy_click"
    const val PDF_save_click = "PDF_save_click"
    const val PDF_edit_click = "PDF_edit_click"
    const val PDF_search_page_click = "PDF_search_page_click"
    const val tool_merge_PDF_file_click = "tool_merge_PDF_file_click"
    const val tool_word_PDF_click = "tool_word_PDF_click"
    const val tool_elxel_PDF_click = "tool_elxel_PDF_click"
    const val tool_image_click = "tool_image_click"
    const val convert_select_file_view = "convert_select_file_view"
    const val convert_select_flie_click = "convert_select_flie_click"
    const val converting_view = "converting_view"
    const val convert_success_view = "convert_success_view"
    const val convert_view_PDF_click = "convert_view_PDF_click"
    const val convert_backtohome_click = "convert_backtohome_click"
    const val merge_select_image_view = "merge_select_image_view"
    const val merge_select_image_click = "merge_select_image_click"
    const val merge_import_image_click = "merge_import_image_click"
    const val merge_image_view = "merge_image_view"
    const val merge_converttoPDF_click = "merge_converttoPDF_click"
    const val merge_cut_click = "merge_cut_click"
    const val merge_save_click = "merge_save_click"
    const val setting_view = "setting_view"
    const val setting_lang_click = "setting_lang_click"
    const val setting_share_click = "setting_share_click"
    const val setting_policy_click = "setting_policy_click"
    const val uninstall_click = "uninstall_click"
    const val uninstall_explore_click = "uninstall_explore_click"
    const val uninstall_try_again_click = "uninstall_try_again_click"
    const val dontuninstall_click = "dontuninstall_click"
    const val still_want_uninstall_click = "still_want_uninstall_click"
    const val reason_uninstall = "reason_uninstall"
    const val uninstall_canel_click = "uninstall_canel_click"

}